const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={page:'dashboard',pages:{tasks:1,pairs:1,reviews:1,codex:1,evidence:1},size:20,preflight:null};
const titles={dashboard:'数据概览',tasks:'题目池',pairs:'A/B 项目',reviews:'GSB 确认',codex:'Codex 作业',evidence:'验收与录像',settings:'系统设置'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=v=>`<span class="badge ${esc(v)}">${esc(v||'—')}</span>`;
const date=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'—';
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({error:`HTTP ${r.status}`}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function notify(msg,error=false){const n=$('#notice');n.textContent=msg;n.className=`notice${error?' error':''}`;setTimeout(()=>n.classList.add('hidden'),5000)}
function loading(){ $('#content').innerHTML='<div class="loading">正在读取数据…</div>' }
async function render(){loading();$('#page-title').textContent=titles[state.page];$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));try{await pages[state.page]()}catch(e){$('#content').innerHTML=`<div class="card empty">读取失败：${esc(e.message)}</div>`}}
const pages={
 dashboard:async()=>{const d=await api('/api/dashboard');const s=d.summary;const max=Math.max(1,...d.trend24h.map(x=>x.count));$('#content').innerHTML=`
  <div class="grid stats"><div class="stat"><small>累计完成 Pair</small><strong>${s.completedPairs}</strong><em>人工确认后的正式记录</em></div><div class="stat"><small>当前活动 Pair</small><strong>${s.activePairs}</strong><em>排队、开发与评审</em></div><div class="stat"><small>已确认 GSB</small><strong>${s.confirmedGsb}</strong><em>A better / Same / B better</em></div><div class="stat"><small>24 小时活跃时段</small><strong>${s.activeHours24h}</strong><em>平均每小时 ${s.hourlyAverage24h}</em></div></div>
  <div class="grid two-col"><div class="card"><h2>24 小时产出趋势</h2><p class="sub">以上海日期归档，统计完成的 A/B Pair</p><div class="bar-chart">${Array.from({length:24},(_,i)=>{const h=String(i).padStart(2,'0');const found=d.trend24h.find(x=>x.hour?.endsWith(h));const n=found?.count||0;return `<div class="bar-wrap" title="${h}:00 · ${n} 条"><div class="bar" style="height:${Math.max(2,n/max*135)}px"></div><small>${i%3===0?h:''}</small></div>`}).join('')}</div></div>
  <div class="card"><h2>GSB 分布</h2><p class="sub">只统计人工确认记录</p>${distribution(d.verdicts)}</div></div>
  <div class="grid two-col" style="margin-top:16px"><div class="card"><h2>Pair 状态</h2><p class="sub">当前状态机中的全部项目</p>${distribution(d.pairStatus)}</div><div class="card"><h2>交付证据</h2><p class="sub">Docker 验收与录像状态</p>${distribution([...d.artifactChecks,...d.recordings])}</div></div>`},
 tasks:async()=>{const p=state.pages.tasks;const d=await api(`/api/tasks?page=${p}&size=${state.size}`);$('#content').innerHTML=`<div class="card"><div class="toolbar"><div class="toolbar-group"><select id="task-status"><option value="">全部状态</option><option>candidate</option><option>ready</option><option>used</option><option>rejected</option></select></div><div class="toolbar-group"><button class="secondary" onclick="importTasks()">导入历史困难题</button><button class="primary" onclick="generateTask()">自动补题</button></div></div>${table(d.items,[['题目',r=>`<div class="title-cell"><strong>${esc(r.title)}</strong><small>${esc(r.prompt)}</small></div>`],['类型',r=>esc(r.task_type)],['难度',r=>`<span class="difficulty">${esc(r.difficulty)}</span>`],['来源',r=>esc(r.source)],['状态',r=>badge(r.status)],['操作',r=>`<button class="tiny" onclick="showTask('${r.id}')">查看</button> ${r.status==='candidate'?`<button class="tiny" onclick="validateTask('${r.id}')">复核</button>`:''} ${r.status==='ready'?`<button class="tiny" onclick="createPair('${r.id}')">创建 Pair</button>`:''}`]])}${pager('tasks',d)}</div>`},
 pairs:async()=>{const d=await api(`/api/pairs?page=${state.pages.pairs}&size=${state.size}`);$('#content').innerHTML=`<div class="card"><div class="toolbar"><div><h2>A/B 项目</h2><p class="sub">同一 main 基线，大写 A/B 分支，两个独立 Claude 容器</p></div></div>${table(d.items,[['项目',r=>`<div class="title-cell"><strong>${esc(r.title)}</strong><small>${esc(r.id)}</small></div>`],['类型 / 难度',r=>`${esc(r.task_type)} · <span class="difficulty">${esc(r.difficulty)}</span>`],['阶段',r=>badge(r.stage)],['状态',r=>badge(r.status)],['GSB',r=>r.verdict?badge(r.verdict):'—'],['操作',r=>`<button class="tiny" onclick="showPair('${r.id}')">打开</button>`]])}${pager('pairs',d)}</div>`},
 reviews:async()=>{const d=await api(`/api/gsb-reviews?page=${state.pages.reviews}&size=${state.size}`);$('#content').innerHTML=`<div class="card"><h2>复核与人工确认</h2><p class="sub">Codex 生成草稿；人工确认前不进入正式完成状态</p>${table(d.items,[['Pair',r=>`<span class="code">${esc(r.pair_id)}</span>`],['结论',r=>badge(r.verdict)],['公开理由',r=>`<div class="review-text">${esc(r.reason)}</div>`],['状态',r=>badge(r.status)],['操作',r=>`<button class="tiny" onclick="reviewGsb('${r.pair_id}')">${r.status==='confirmed'?'查看':'确认'}</button>`]])}${pager('reviews',d)}</div>`},
 codex:async()=>{const d=await api(`/api/codex-jobs?page=${state.pages.codex}&size=${state.size}`);$('#content').innerHTML=`<div class="card"><h2>Codex CLI 作业</h2><p class="sub">除 A/B 开发外的模型节点均在这里留痕</p>${table(d.items,[['作业',r=>`<div class="title-cell"><strong>${esc(r.job_type)}</strong><small>${esc(r.id)}</small></div>`],['模型',r=>esc(r.model)],['推理强度',r=>badge(r.reasoning_effort)],['状态',r=>badge(r.status)],['尝试',r=>r.attempt_count],['开始时间',r=>date(r.started_at||r.created_at)],['错误',r=>`<div class="title-cell"><small>${esc(r.error)}</small></div>`]])}${pager('codex',d)}</div>`},
 evidence:async()=>{const [checks,recs]=await Promise.all([api(`/api/artifact-checks?page=${state.pages.evidence}&size=10`),api(`/api/recordings?page=${state.pages.evidence}&size=10`)]);$('#content').innerHTML=`<div class="grid two-col"><div class="card"><h2>Docker 产物验收</h2><p class="sub">必须清洁构建、启动、健康并完成清理</p>${table(checks.items,[['Pair / Arm',r=>`${esc(r.pair_id)} · ${r.arm}`],['提交',r=>`<span class="code">${esc((r.commit_sha||'').slice(0,10))}</span>`],['状态',r=>badge(r.status)],['时间',r=>date(r.finished_at)]])}</div><div class="card"><h2>真实操作录像</h2><p class="sub">1280×720，时长少于 90 秒</p>${table(recs.items,[['Pair / Arm',r=>`${esc(r.pair_id)} · ${r.arm}`],['规格',r=>`${r.width}×${r.height} · ${r.duration_seconds}s`],['状态',r=>badge(r.status)],['文件',r=>`<span class="code">${esc(r.path)}</span>`]])}</div></div>`},
 settings:async()=>{const [s,p]=await Promise.all([api('/api/settings'),api('/api/preflight')]);state.preflight=p;$('#runtime-summary').textContent=`Codex ${s.codex_model} · Claude ${s.claude_model}`;$('#content').innerHTML=`<div class="card"><h2>运行环境预检</h2><p class="sub">Git、Codex 和 Claude 容器相互独立</p><div class="preflight">${preflightCard('Git / GitHub',p.git?.ok,p.git?.gh?.account||p.git?.gh?.error||'未认证')}${preflightCard('Codex CLI',p.codex?.ok,p.codex?.version||p.codex?.error)}${preflightCard('Claude Docker',p.claude?.ok,p.claude?.image_id||p.claude?.image)}</div></div><div class="card" style="margin-top:16px"><h2>默认模型与流程参数</h2><p class="sub">Claude 只用于 A/B 开发；其余模型节点全部使用 Codex CLI</p><div class="setting-list">${setting('codex_model','Codex 默认模型',s.codex_model,'出题、复核、找 Bug、GSB 与下一步判断')}${setting('codex_default_effort','Codex 常规强度',s.codex_default_effort,'默认 medium')}${setting('codex_bug_effort','找 Bug 强度',s.codex_bug_effort,'默认 high')}${setting('claude_model','Claude 开发模型',s.claude_model,'仅用于 A/B 开发')}${setting('claude_image','Claude 容器镜像',s.claude_image,'从现系统部署配置读取')}${setting('task_generation_max_parallel','出题并发',s.task_generation_max_parallel,'与开发并发分开')}${setting('task_pool_min_ready','题库低水位',s.task_pool_min_ready,'低于此值自动补题')}${setting('task_pool_target_ready','题库目标水位',s.task_pool_target_ready,'每轮补到此数量')}${setting('max_pairs_parallel','Pair 并发',s.max_pairs_parallel,'每个 Pair 包含 A/B 两个容器')}${setting('git_author_name','Git 提交人',s.git_author_name,'默认刘昱')}${setting('git_author_email','Git 提交邮箱',s.git_author_email,'创建远端仓库前必填')}${setting('github_owner','GitHub Owner',s.github_owner,'留空时使用 gh 当前账号')}${setting('github_visibility','仓库可见性',s.github_visibility,'private 或 public')}${setting('repository_prefix','仓库名前缀',s.repository_prefix||'','可为空')}</div><div style="margin-top:18px"><button class="primary" onclick="saveSettings()">保存设置</button></div></div>`}
};
function distribution(rows){if(!rows.length)return '<div class="empty">还没有数据</div>';const max=Math.max(...rows.map(x=>x.count));return `<div class="legend-list">${rows.map(x=>`<div class="legend-row"><span>${esc(x.verdict||x.status||x.task_type)}</span><div class="legend-track"><div class="legend-fill" style="width:${x.count/max*100}%"></div></div><b>${x.count}</b></div>`).join('')}</div>`}
function table(rows,cols){if(!rows.length)return '<div class="empty">暂无记录</div>';return `<table><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c[1](r)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function pager(name,d){const pages=Math.max(1,Math.ceil(d.total/d.size));return `<div class="pagination"><span>共 ${d.total} 条 · 第 ${d.page}/${pages} 页</span><button class="tiny" ${d.page<=1?'disabled':''} onclick="goPage('${name}',${d.page-1})">上一页</button><button class="tiny" ${d.page>=pages?'disabled':''} onclick="goPage('${name}',${d.page+1})">下一页</button></div>`}
function preflightCard(name,ok,detail){return `<div class="preflight-item"><strong>${esc(name)}</strong><div class="${ok?'ok':'bad'}">${ok?'● 可用':'● 需要配置'}</div><small>${esc(detail||'—')}</small></div>`}
function setting(key,label,value,help){return `<div class="setting"><label for="set-${key}">${esc(label)}</label><input id="set-${key}" data-setting="${key}" value="${esc(value)}"><small>${esc(help)}</small></div>`}
async function importTasks(){try{const d=await api('/api/tasks/import-historical',{method:'POST',body:JSON.stringify({limit:1000})});notify(`导入 ${d.imported} 条，跳过 ${d.skipped} 条`);render()}catch(e){notify(e.message,true)}}
async function generateTask(){try{const d=await api('/api/tasks/generate',{method:'POST',body:JSON.stringify({count:1,taskType:'zero_to_one'})});notify(`补题作业已启动：${d.operationId}`);poll(d.operationId)}catch(e){notify(e.message,true)}}
async function validateTask(id){try{const d=await api(`/api/tasks/${id}/validate`,{method:'POST',body:'{}'});notify('难度、禁题、查重和基线复核已启动');poll(d.operationId)}catch(e){notify(e.message,true)}}
async function createPair(id){try{const d=await api('/api/pairs',{method:'POST',body:JSON.stringify({taskId:id})});notify(`已创建 ${d.id}`);state.page='pairs';render()}catch(e){notify(e.message,true)}}
async function showTask(id){try{const d=await api(`/api/tasks?page=1&size=100`);const t=d.items.find(x=>x.id===id);showDialog(`<h2>${esc(t?.title||id)}</h2><div class="kv"><b>类型</b><span>${esc(t?.task_type)}</span></div><div class="kv"><b>难度</b><span>${esc(t?.difficulty)}</span></div><div class="kv"><b>状态</b><span>${badge(t?.status)}</span></div><div class="kv"><b>题面</b><div class="wrap">${esc(t?.prompt)}</div></div><div class="kv"><b>未通过原因</b><span>${esc(t?.rejection_reason||'—')}</span></div>`)}catch(e){notify(e.message,true)}}
async function showPair(id){try{const d=await api(`/api/pairs/${id}`);const repo=d.repository;const buttons=pairButtons(d);showDialog(`<h2>${esc(d.task.title)}</h2><p>${badge(d.status)} ${badge(d.stage)}</p><div class="detail-grid"><div class="detail-item"><label>Pair ID</label><strong class="code">${esc(d.id)}</strong></div><div class="detail-item"><label>共同基线</label><strong class="code">${esc(d.baseline_sha||'待创建')}</strong></div><div class="detail-item"><label>远端仓库</label><strong class="code">${esc(repo?.remote_url||'待创建')}</strong></div><div class="detail-item"><label>分支</label><strong>main / A / B</strong></div></div><h3>A/B 执行</h3>${table(d.arms,[['Arm',r=>r.arm],['模型',r=>esc(r.model)],['镜像',r=>esc(r.image)],['状态',r=>badge(r.status)],['工作区',r=>`<span class="code">${esc(r.workspace_path)}</span>`]])}<div style="margin-top:18px">${buttons}</div>`)}catch(e){notify(e.message,true)}}
function pairButtons(d){const id=d.id;if(d.stage==='repository')return `<button class="primary" onclick="pairAction('${id}','prepare')">创建 GitHub 仓库并准备 A/B</button>`;if(d.stage==='ready_to_start')return `<button class="primary" onclick="pairAction('${id}','start')">并行启动 A/B 开发</button>`;if(d.stage==='recording'){const by=Object.fromEntries((d.recordings||[]).map(x=>[x.arm,x]));return ['A','B'].map(a=>by[a]?.status==='recording'?`<button class="danger" onclick="recordAction('${id}','${a}','stop')">停止 ${a} 录像</button>`:by[a]?.status==='passed'?`<span class="badge passed">${a} 录像通过</span>`:`<button class="primary" onclick="recordAction('${id}','${a}','start')">录制 ${a} 真实操作</button>`).join(' ')}if(d.stage==='gsb_ready')return `<button class="primary" onclick="pairAction('${id}','gsb')">生成 GSB 草稿</button>`;return `<span class="badge ${esc(d.status)}">当前阶段：${esc(d.stage)}</span>`}
async function recordAction(id,arm,action){try{$('#dialog').close();await api(`/api/pairs/${id}/recordings/${arm}/${action}`,{method:'POST',body:JSON.stringify({x:0,y:0})});notify(action==='start'?`${arm} 录像已开始，请在 85 秒内完成真实点击演示`:`${arm} 录像正在收尾校验`);setTimeout(render,1600)}catch(e){notify(e.message,true)}}
async function pairAction(id,action){try{$('#dialog').close();const d=await api(`/api/pairs/${id}/${action}`,{method:'POST',body:'{}'});notify(`操作已启动：${d.operationId}`);poll(d.operationId)}catch(e){notify(e.message,true)}}
async function reviewGsb(id){try{const d=await api(`/api/pairs/${id}`),g=d.gsb;if(!g)throw new Error('尚未生成 GSB 草稿');showDialog(`<h2>人工确认 GSB</h2><p>${esc(d.task.title)}</p><div class="choice-row">${['A better','Same','B better'].map(v=>`<label class="choice"><input type="radio" name="verdict" value="${v}" ${g.verdict===v?'checked':''}>${v}</label>`).join('')}</div><textarea class="review-input" id="gsb-reason">${esc(g.reason)}</textarea><p class="sub"><span id="gsb-count">${g.reason.length}</span>/600 字符，必须为单段且不能含反引号</p><input id="confirmed-by" value="人工确认" placeholder="确认人"><button type="button" class="primary" style="margin-left:8px" onclick="confirmGsb('${id}')">确认并完成</button>`);$('#gsb-reason').addEventListener('input',e=>$('#gsb-count').textContent=e.target.value.length)}catch(e){notify(e.message,true)}}
async function confirmGsb(id){const verdict=$('input[name=verdict]:checked')?.value,reason=$('#gsb-reason').value,confirmedBy=$('#confirmed-by').value;try{await api(`/api/pairs/${id}/gsb/confirm`,{method:'POST',body:JSON.stringify({verdict,reason,confirmedBy})});$('#dialog').close();notify('GSB 已人工确认，Pair 已完成');render()}catch(e){notify(e.message,true)}}
async function saveSettings(){const body={};$$('[data-setting]').forEach(i=>body[i.dataset.setting]=['task_generation_max_parallel','task_pool_min_ready','task_pool_target_ready','max_pairs_parallel'].includes(i.dataset.setting)?Number(i.value):i.value);try{await api('/api/settings',{method:'POST',body:JSON.stringify(body)});notify('设置已保存，新作业将使用这些值');render()}catch(e){notify(e.message,true)}}
async function poll(id){for(let i=0;i<120;i++){await new Promise(r=>setTimeout(r,1500));const d=await api(`/api/operations/${id}`);if(d.status==='completed'){notify('后台操作已完成');return render()}if(d.status==='failed'){return notify(d.error,true)}}notify('操作仍在后台运行，可在相应页面继续查看')}
function goPage(name,page){state.pages[name]=page;render()}function showDialog(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal()}
$$('#nav button').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});$('#refresh').onclick=render;setInterval(()=>$('#clock').textContent=new Date().toLocaleString('zh-CN'),1000);render();api('/api/settings').then(s=>$('#runtime-summary').textContent=`Codex ${s.codex_model} · Claude ${s.claude_model}`).catch(()=>{});
